--- 
version: "2.0"
services: 
  qbittorrent: 
    image: "linuxserver/qbittorrent:amd64-latest"
    container_name: "qbittorrent"
    ports: 
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      WEBUI_PORT: 8080
    volumes: 
      - "/home/lgallard/Downloads/:/downloads"
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: "nginx"
    ports:
      - "80:80"
